### ISSUE TITLE
Graphical help

### ISSUE THREAD

**Issue by RunawayHyena** [AyronK/ayronk#1]
Hey I don't really know if this is the correct way of contacting somebody on GitHub but I've seen your aRPG Seasons Timeline site and I quite like it, if you want help with some graphical design to make it look cooler you can send me a message. I will specify that I am not looking for an opportunity to make money, I just want to help! If you are interested you can contact me on Discord @pinkunobara.

Have a good day!

**Comment by AyronK** [comment]
@PINKUNOBARA I've sent you an invite on discord, we can discuss the options. Thank you for reaching out!
